### ISSUE TITLE
connection string using wallet

### ISSUE THREAD

**Issue by bhargaviaaa** [mattn/go-oci8#360] opened 2019-10-31 09:04 UTC
Is it possible to connect oracle DB using wallet? If yes please provide example.

**Comment by MichaelS11** [comment] 2019-10-31 15:17
It should work but I have not tested it myself. Make sure to setup sqlnet.ora and tnsnames.ora. Do not put username and password in connection string. Just pass the tnsname from the tnsnames.ora file.

https://docs.oracle.com/en/cloud/paas/atp-cloud/atpug/connect-preparing.html#GUID-EFAFA00E-54CC-47C7-8C71-E7868279EF3B

**Comment by cjbj** [comment] 2019-10-31 23:04
Not all wallets have usernames and passwords so sometimes they are needed in the application parameters.  For example when connecting to Oracle Cloud DBs the wallets are only used to enable SSL/TLS.  If you are using Oracle cloud, the videos https://www.youtube.com/watch?v=5HlaPpY6gNw  and https://www.youtube.com/watch?v=WaVdFZ90Jj8 have some content showing what to do with the wallets.  The steps are common for all C based Oracle DB drivers, including go-oci8.

**Comment by bhargaviaaa** [comment] 2019-11-04 07:09
Not working.  "Unable to connect to oracle:ORA-12154: TNS:could not resolve the connect identifier specified"
Have correct entries in sqlnet.ora and tnsnames.ora files.
Connection string format used is "/@<tns_entryname>"

**Comment by MichaelS11** [comment] 2019-11-04 10:27
Just put in the tnsname, no /@

**Comment by bhargaviaaa** [comment] 2019-11-05 04:24
Unable to connect to oracle:ORA-01005: null password given; logon denied

**Comment by MichaelS11** [comment] 2019-11-05 05:06
What happens when you use sqlplus?

**Comment by bhargaviaaa** [comment] 2019-11-05 08:00
sqlplus works with /@tnsname

**Comment by MichaelS11** [comment] 2019-11-05 10:08
What happens with sqlplus with just tnsname?

**Comment by bhargaviaaa** [comment] 2019-11-07 06:34
Fails to connect

**Comment by MichaelS11** [comment] 2019-11-07 17:53
@cjbj Any thoughts on where the issue is? Something needs to change in the go-oci8 (oic) code I assume?

**Comment by cjbj** [comment] 2019-11-08 02:38
@bhargaviaaa what kind of wallet do you have - does it have username & password, or does it just set up TLS?

@MichaelS11 If the wallet has username & password, how is OCI_CRED_EXT being set?  E.g. via an [explicit flag ](https://oracle.github.io/node-oracledb/doc/api.html#propdbisexternalauth).  Also see p 116 of http://www.oracle.com/technetwork/topics/php/underground-php-oracle-manual-098250.html

**Comment by bhargaviaaa** [comment] 2019-11-14 08:37
Does not include username and password

**Comment by MichaelS11** [comment] 2019-11-20 00:31
@cjbj 
It is being set here:
https://github.com/mattn/go-oci8/blob/cbd8d5bc1da03767b2584d4c2e921f2711d9aeb1/oci8.go#L319-L334

**Comment by MichaelS11** [comment] 2019-11-29 06:48
@cjbj So what does that mean?

**Comment by MichaelS11** [comment] 2019-12-03 16:44
@cjbj Any more thoughts?

**Comment by cjbj** [comment] 2019-12-05 04:03
@MichaelS11 can you check how it's being done in https://github.com/oracle/odpi/blob/v3.3.0/src/dpiConn.c#L542 and https://github.com/oracle/odpi/blob/v3.3.0/src/dpiConn.c#L389 ?

**Comment by MichaelS11** [comment] 2019-12-07 18:46
@cjbj I am not sure what part of that code you are trying to point out. For the OCISessionBegin the credt should be set to OCI_CRED_EXT which seems correct. What other part of the code is important for connecting with wallet?

**Comment by cjbj** [comment] 2019-12-09 03:32
It does seem like that is all that should be needed in the code.  Have you created a wallet for testing? https://cx-oracle.readthedocs.io/en/latest/user_guide/connection_handling.html#using-an-oracle-wallet-for-external-authentication

**Comment by MichaelS11** [comment] 2019-12-09 17:51
I have not but @bhargaviaaa and other people have.

**Comment by MichaelS11** [comment] 2019-12-18 00:41
@cjbj Remember this issues said they were having issues as well https://github.com/mattn/go-oci8/issues/329

**Comment by cjbj** [comment] 2019-12-18 00:54
@MichaelS11 someone will need to do some debugging and comparison on this.

**Comment by MichaelS11** [comment] 2019-12-18 00:55
Sure, looking for some pointers and how to go about that?

**Comment by cjbj** [comment] 2019-12-18 00:57
Run one of the other working drivers and see what it passes?  But you'll need a wallet.

**Comment by MichaelS11** [comment] 2019-12-18 01:08
Not sure how that is going to help debug this driver. That will tell me that my wallet works but not what is wrong with this driver.

**Comment by cjbj** [comment] 2019-12-18 02:01
@MichaelS11 I'm not sure what you want me to do.  I can advise and point to examples, but I'm not able to run your code in a debugger.

**Comment by MichaelS11** [comment] 2019-12-18 02:05
I am looking for help with debugging Oracle OCI code. This driver is just a interface between the Go SQL packages and the Oracle OCI code/package. Just need normal Oracle OCI help / troubleshooting steps for the OCI driver. Can even think about it as if it was C++ code if that helps.

**Comment by cjbj** [comment] 2019-12-18 03:18
@MichaelS11 send me email?

**Comment by MichaelS11** [comment] 2019-12-20 19:58
@bhargaviaaa 

I got wallet login working on a Oracle database installed on Linux.

---

Wallet create example (replace type_*_here lines):
```
mkstore -wrl type_path_here -create

mkstore -wrl type_path_here -createCredential type_tnsnames_entry_name_here type_database_username_here

export TNS_ADMIN=type_path_here

echo '
WALLET_LOCATION = (SOURCE = (METHOD = FILE) (METHOD_DATA = (DIRECTORY = type_path_here )))
SQLNET.WALLET_OVERRIDE = TRUE
SSL_CLIENT_AUTHENTICATION = FALSE
' > type_path_here/sqlnet.ora
```

Go sql open example (replace type_tnsname_entry_name_here):

`db, err := sql.Open("oci8", "@type_tnsname_entry_name_here")`

---

So I think the go-oci8 driver is working unless more information can be provided showing otherwise.

**Comment by MichaelS11** [comment] 2020-01-15 16:42
@mattn Close this?

**Closed** 2020-01-16 05:05 UTC
