### ISSUE TITLE
ORA-01406 when reading a large string with Queryrow(x)

### ISSUE THREAD

**Issue by thigaz** [mattn/go-oci8#308] opened 2018-12-07 19:49 UTC
I was receiving the error above and coudn't figure out how to change the limit of the receiver. When I moved to Query(x) and Scan I stopped getting error, but received zero rows as response.

The string was from a VARCHAR2 with 2054 characters (the database field has a limitation of 2000 chars, don't know how it passed the limit, but there it was)

(the error ocurred with both queryrow and queryrowx)

**Comment by mattn** [comment] 2018-12-13 01:00
Please show me minimal code to reproduce.

**Comment by MichaelS11** [comment] 2018-12-19 17:06
@thigaz Could you please provide SQL and Go code to reproduce, or close this issue?

**Comment by thigaz** [comment] 2018-12-26 16:30
> @thigaz Need sql as well.

It's in the body of the message:

`SELECT t.TDAT
FROM pmobjt a, pmtext t
WHERE a.OBJT = 1628249
AND a.cmmt = t.txid
ORDER BY t.numr`

**Comment by MichaelS11** [comment] 2018-12-26 17:44
@thigaz All the SQL. In this case it looks like the two create tables and all the relevant inserts.

But really want is wanted is a self contained example, with all the needed SQL, create tables, insert statements, select statements, any PL/SQL, etc.

**Comment by thigaz** [comment] 2018-12-26 18:07
It's a SAP PowerDesigner product database which I'm querying some fields. I didn't create the table nor its data. I'm able to retrieve the data using Goracle, but not with OCI8.
I'll create a custom DB and see if I can simulate the same error.

**Comment by MichaelS11** [comment] 2018-12-26 18:11
Thank you. With a working example that reproduces the error, makes it so we can help reproduce and hopefully fix the issue.

**Comment by MichaelS11** [comment] 2019-01-04 12:40
This may just be a duplicate of https://github.com/mattn/go-oci8/issues/306 . If so, close this?

**Comment by MichaelS11** [comment] 2019-01-11 10:57
@mattn Close this?

**Comment by thigaz** [comment] 2019-01-11 13:42
You guys can close it. It's been some rough months here and I don't know when I'll have time to focus on this issue. If you can create a VARCHAR2 column limited to 2000 chars with 2024+ chars and read it normally, the problem may be on my DB.

Anyway, thanks for being interested on my problem!

**Comment by MichaelS11** [comment] 2019-01-11 16:37
@thigaz Welcome. Could you close it?

**Closed** 2019-01-15 00:12 UTC
Labels: wait
