### ISSUE TITLE
All chinese character show as '?????????????'

### ISSUE THREAD

**Issue by toplinuxsir** [mattn/go-oci8#340] opened 2019-05-07 23:44 UTC
All chinese character show as '?????????????'

I set the env with  :
`
os.Setenv("NLS_LANG", "SIMPLIFIED CHINESE_CHINA.AL32UTF8")
`
and then query and scan
But all the chinese character show as ?????

Can anybody help me ?
Thanks!

**Comment by MichaelS11** [comment] 2019-05-07 23:50
Did you try the default AMERICAN_AMERICA.AL32UTF8 ?

**Comment by toplinuxsir** [comment] 2019-05-08 00:29
I have tested with "AMERICAN_AMERICA.AL32UTF8", But with same result!

**Comment by MichaelS11** [comment] 2019-05-08 00:56
It is hard to say where the issue is located. What language is the database in? Do you have reproducible code where you insert the characters and then select the characters?

Also would suggest look over past issues, this is a common issue that comes up.

**Comment by toplinuxsir** [comment] 2019-05-08 01:07
I switch to goracle ,Everything is ok

**Comment by toplinuxsir** [comment] 2019-05-08 04:09
MY database language 
`
SELECT sys_context('userenv','language') from dual;
` output 
`
SIMPLIFIED CHINESE_CHINA.AL32UTF8
`
Anyway , Hope to fix the bug .

**Comment by MichaelS11** [comment] 2019-05-08 20:33
@toplinuxsir Sounds like you are going to use goracle instead. Can you please close this issue?

**Comment by robinsoon** [comment] 2019-05-13 09:21
Incorrect  Oracle  driver version， or Multiple drivers are installed in the system.
UTF8 ，  Client and server configurations must be consistent。

**Comment by MichaelS11** [comment] 2019-05-13 20:36
@mattn Close this? Not much else we can do with this issue at this time.

**Closed** 2019-05-14 00:37 UTC
